spring:
    shardingsphere:
        datasource:
            dsmaster0:
                driver-class-name: com.mysql.jdbc.Driver
                password: 123456
                type: com.alibaba.druid.pool.DruidDataSource
                url: jdbc:mysql://127.0.0.1:3306/dsmaster0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
                username: root
            dsmaster0-slave:
                driver-class-name: com.mysql.jdbc.Driver
                password: 123456
                type: com.alibaba.druid.pool.DruidDataSource
                url: jdbc:mysql://127.0.0.1:3306/dsmaster0-slave?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
                username: root

            dsmaster1:
                driver-class-name: com.mysql.jdbc.Driver
                password: 123456
                type: com.alibaba.druid.pool.DruidDataSource
                url: jdbc:mysql://127.0.0.1:3306/dsmaster1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
                username: root
            dsmaster1-slave:
                driver-class-name: com.mysql.jdbc.Driver
                password: 123456
                type: com.alibaba.druid.pool.DruidDataSource
                url: jdbc:mysql://127.0.0.1:3306/dsmaster1-slave?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
                username: root

            names: dsmaster0,dsmaster1,dsmaster0-slave,dsmaster1-slave

        sharding:
            binding-tables: health_record,health_task
            broadcast-tables: health_level
            default-database-strategy:
                inline:
                    algorithm-expression: 'dsmaster$->{user_id % 2} '
                    sharding-column: user_id
            master-slave-rules:
                dsmaster0:
                    master-data-source-name: dsmaster0
                    slave-data-source-names: dsmaster0-slave
                dsmaster1:
                    master-data-source-name: dsmaster1
                    slave-data-source-names: dsmaster1-slave
            tables:
                health_record:
                    actual-data-nodes: dsmaster$->{0..1}.health_record$->{0..1}
                    key-generator:
                        column: record_id
                        props:
                            worker:
                                id: 33
                        type: SNOWFLAKE
                    table-strategy:
                        inline:
                            algorithm-expression: health_record$->{record_id % 2}
                            sharding-column: record_id
                health_task:
                    actual-data-nodes: dsmaster$->{0..1}.health_task$->{0..1}
                    key-generator:
                        column: task_id
                        props:
                            worker:
                                id: 33
                        type: SNOWFLAKE
                    table-strategy:
                        inline:
                            algorithm-expression: health_task$->{record_id % 3}
                            sharding-column: record_id

